### PR TITLE
Requests implemented

### PR DESCRIPTION
**Pull request by klarkent**
Hi Valery I added some modifications as you can see. For me it is well working but maybe you should give it an eye to check for errors. Hope this will be appreciated

In short:
1. Edited some logs to filter them by type
2. Added expire callback function and return cookie data + sessionID
3. Added info in readme :+1:

### CODE REVIEW

**Comment by valery-barysok** [comment]
And you need to split your pull request. you have two distinct changes: add expire callback and log messages.

**Comment by valery-barysok** [comment]
In any case place where you put your code for expire callback is wrong. expired function can be called in any place but not just here.

**Comment by klarkent** [comment]
Ok I'll try with emit this afternoon or tomorrow. I actually inserted the expireCallback into `destroyIfExpired` as I intented to use expireCallback to be called only once when the session is actually deleted. Maybe I should have called it deleteCallback instead.
About the expiration check I saw expired and isExpired so I should trigger an emit event there I think.
About splitting the pull request I don't know how to do it. I think that I should split the 0c03eaa commit first, right?

**Comment by valery-barysok** [comment]
simplest way just create two new branches and do commits again and then do pull requests.

**Pull request closed without merging**
