### PR TITLE
allow custom encoders, text encodings, and file extensions

### PR DESCRIPTION
**Pull request by TYoung86**
adds new options: encoder, decoder, encoding, encryptEncoding, fileExtension
does not introduce any breaking changes.
adds 3 new test cases. passes 35/35 tests.
does not test encoders other than JSON, but intent is to use with CBOR, BSON, etc.

### CODE REVIEW

**Comment by TYoung86** [comment]
https://github.com/valery-barysok/session-file-store/issues/43

**Comment by TYoung86** [comment]
going to add documentation, and test case covering cbor, found an untested edge case on text encoding

**Comment by TYoung86** [comment]
think that covers documentation, should be good to go

**Comment by TYoung86** [comment]
reviewed encryption implementation. not happy. I will submit a separate pull request to add an option to specify a key retrieval function / transform so the session id (the file name) isn't the only thing protecting the file. the default will be sessionId => sessionId (a no op), and a recommendation for sessionId => externalKey+sessionId ...

**Comment by valery-barysok** [comment]
available in 1.0.0 version

**Pull request merged**
